//#define ENABLE_OPEN_MULTIPLE
//#define _IMPROVED_PACKET_ENCRYPTION_
//define ENABLE_SEQUENCE_SYSTEM
//#define ENABLE_GUI_SHOWER
//#define ENABLE_WOLFMAN

#define CHARACTER_NAME_MAX_LEN	48
#define MAX_HIT_COUNT 24 //16
#define HORSE_SKILL_SLOT 107
#define LSS_SECURITY_KEY "1234abcd5678efgh"
#define CLIENT_VERSION "20181010"
#define DONT_LOAD_FROM_D_PATH "TRUE" // TRUE or FALSE
#define HIDE_GRANNY_SYSERR
#define ENABLE_TARGET_INFO
#define ENABLE_SHINING_SYSTEM
#define ENABLE_LZ4_PACK_COMPRESSION
#define ENABLE_ELEMENT_TARGET
#define ENABLE_STOP_COLISSION_GLOBAL
#define ENABLE_PACKET_LIMIT
#define ENABLE_RENDERING_ONLY_IN_AREA
#define ITEM_CHECKINOUT_UPDATE
#define ENABLE_TEXT_RENEWAL
//#define ENABLE_LOCAL_FILE_LOADING
#define ENABLE_CHEST_DROP
#define ENABLE_SWITCHBOT
#define ENABLE_WALLHACK_FOR_GM
#define ENABLE_EXTENDED_SOCKETS
#define ENABLE_HUNTING_SYSTEM
#define ENABLE_ASLAN_BUFF_NPC_SYSTEM
#ifdef ENABLE_ASLAN_BUFF_NPC_SYSTEM
	#define ASLAN_BUFF_NPC_ENABLE_EXPORT
	#define ASLAN_BUFF_NPC_ENABLE_EXPORT_COST
	#define ASLAN_BUFF_NPC_USE_SKILL_TECH_LEVEL
#endif
#define ENABLE_FOV
#define ENABLE_ITEMSHOP
#define __BL_DROP_DESTROY_TIME__	// Drop Time Items

#define ENABLE_SPECIAL_INVENTORY
#define ENABLE_INVENTORY_SORT
#define HIGHLIGHT_SLOT
#define WJ_ENABLE_TRADABLE_ICON
#define __RENEWAL_NOTICE__
#define ENABLE_VOTE_FOR_BONUS