#pragma once

enum 
{
	PARTY_CAN_JOIN_MAX_LEVEL	= 30,
	DEFAULT_ATTACK_SPEED		= 180,
	DEFAULT_MOVE_SPEED			= 320,
	MOVEMENT_SPEED_LIMIT		= 320,
	MAX_MEMBER_INTRO_PARTY		= 8,
	MAX_ITEM_STACK				= 5000,
};

//#define _IMPROVED_PACKET_ENCRYPTION_
//#define ENABLE_MIRRORING_PROTO
//#define ENABLE_SEQUENCE_SYSTEM
//#define ENABLE_WOLFMAN
//#define ENABLE_OPEN_MULTIPLE

#define ENABLE_UDP_BLOCK
#define CLIENT_VERSION "20181010"
#define LSS_SECURITY_KEY "1234abcd5678efgh"

#define ENABLE_TARGET_INFO
#define ENABLE_MASTER_SKILLBOOK_NO_STEPS
#define ITEM_CHECKINOUT_UPDATE
#define ENABLE_INSTANT_5_BONUS
#define ENABLE_XOSHIRO
#define ENABLE_EXTENDED_SOCKETS
#define ENABLE_SWITCHBOT

#define ENABLE_HUNTING_SYSTEM
#ifdef ENABLE_HUNTING_SYSTEM
	#define HUNTING_MISSION_COUNT 90
	#define HUNTING_MONEY_TABLE_SIZE 9
	#define HUNTING_EXP_TABLE_SIZE 9
#endif

#define ENABLE_ASLAN_BUFF_NPC_SYSTEM
#ifdef ENABLE_ASLAN_BUFF_NPC_SYSTEM
	// You can Deactivate or Activate this
	#define ASLAN_BUFF_NPC_USE_SUMMON_LEVEL_CAP
	#define ASLAN_BUFF_NPC_USE_SKILL_17_TO_M
	#define ASLAN_BUFF_NPC_USE_SKILL_TECH_LEVEL
	#define ASLAN_BUFF_NPC_ENABLE_EXPORT
	#define ASLAN_BUFF_NPC_ENABLE_EXPORT_COST
	
	// Config values ( !!! no deactivate this defines !!! ) 
	#define ASLAN_BUFF_NPC_SEAL_VNUM 71999
	#define ASLAN_BUFF_NPC_MAX_LV 99
	#define ASLAN_BUFF_NPC_MAX_LV_CAP 30 			// is active ASLAN_BUFF_NPC_USE_SUMMON_LEVEL_CAP -> Maximum cap where you can call the buff. ( 0 = you can call to your own level )
	#define ASLAN_BUFF_NPC_START_INT 4
	#define ASLAN_BUFF_NPC_MAX_INT 140
	#define ASLAN_BUFF_NPC_MIN_HP_PERC_USE_SKILL_HEAL 30
	#define ASLAN_BUFF_EXP_RING_ITEM_1 72001
	#define ASLAN_BUFF_EXP_RING_ITEM_2 72002
	#define ASLAN_BUFF_EXP_RING_ITEM_3 72003
#endif
#define ENABLE_ITEMSHOP
#define __BL_DROP_DESTROY_TIME__	// Drop Time Items

#define ENABLE_SPECIAL_INVENTORY
#define ENABLE_INVENTORY_SORT
#define HIGHLIGHT_SLOT
#define WJ_ENABLE_TRADABLE_ICON